/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hoYvxPYcmIO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

export function Textarea() {
  return (
    <div className="grid gap-2">
      <Label htmlFor="message">Your Message</Label>
      <Textarea
        id="message"
        placeholder="Type your message here..."
        className="resize-y min-h-[100px] p-4 rounded-md border border-muted focus:border-primary focus:ring-primary"
        rows={3}
      />
      <div className="flex justify-end text-muted-foreground text-sm">
        <span>0</span> / 500 characters
      </div>
    </div>
  )
}
