import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import NavBar from "@/components/NavBar";
import SideNav from "@/components/side-nav";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import Providers from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hello World!!!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={cn("min-h-screen bg-background antialiased", inter.className)}>
        <Providers>
          <SessionProvider>
            <NavBar />
            <main className=" w-full h-full overflow-y-hidden flex items-start pt-14">
              <SideNav />
              <Toaster />
              <div className=" flex-grow bg-gray-50">{children}</div>
            </main>
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
